"""Output formatting for meld results."""

import json
from datetime import datetime

from meld.data_models import SessionMetadata


class OutputFormatter:
    """Formats meld output in various formats."""

    def __init__(self, verbose: bool = False) -> None:
        """Initialize formatter."""
        self._verbose = verbose

    def format_final_plan(
        self,
        plan: str,
        session: SessionMetadata,
        verbose_outputs: list[str] | None = None,
    ) -> str:
        """Format the final plan output as markdown."""
        lines = [
            "# Meld Plan Output",
            "",
            f"**Session ID:** {session.session_id}",
            f"**Task:** {session.task[:100]}{'...' if len(session.task) > 100 else ''}",
            f"**Rounds:** {session.rounds_completed}/{session.max_rounds}",
            f"**Converged:** {'Yes' if session.converged else 'No'}",
            f"**Advisors:** {', '.join(session.advisors_participated) or 'None'}",
            "",
            "---",
            "",
            "## Final Plan",
            "",
            plan,
            "",
        ]

        if self._verbose and verbose_outputs:
            lines.extend([
                "---",
                "",
                "## Raw Advisor Outputs",
                "",
            ])
            for output in verbose_outputs:
                lines.append(output)
                lines.append("")

        lines.extend([
            "---",
            "",
            f"*Generated by Meld at {datetime.utcnow().isoformat()}Z*",
        ])

        return "\n".join(lines)

    def format_json_summary(self, session: SessionMetadata) -> str:
        """Format session metadata as JSON."""
        data = {
            "session_id": session.session_id,
            "task": session.task,
            "rounds_completed": session.rounds_completed,
            "max_rounds": session.max_rounds,
            "converged": session.converged,
            "advisors_participated": session.advisors_participated,
            "started_at": session.started_at.isoformat() if session.started_at else None,
            "completed_at": session.completed_at.isoformat() if session.completed_at else None,
            "status": session.status,
        }
        return json.dumps(data, indent=2)

    def format_quiet_output(self, plan: str) -> str:
        """Format minimal output for quiet mode."""
        return plan
